//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcfServiceException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class WcfServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception exceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception exception {
            get {
                return this.exceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.exceptionField, value) != true)) {
                    this.exceptionField = value;
                    this.RaisePropertyChanged("exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Add", ReplyAction="http://tempuri.org/IUserService/AddResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.ServiceReference.WcfServiceException), Action="http://tempuri.org/IUserService/AddWcfServiceExceptionFault", Name="WcfServiceException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        int Add(UserStorage.Entity.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Add", ReplyAction="http://tempuri.org/IUserService/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(UserStorage.Entity.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Search", ReplyAction="http://tempuri.org/IUserService/SearchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.ServiceReference.WcfServiceException), Action="http://tempuri.org/IUserService/SearchWcfServiceExceptionFault", Name="WcfServiceException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        System.Collections.Generic.List<UserStorage.Entity.User> Search(UserStorage.Entity.UserCriteria criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Search", ReplyAction="http://tempuri.org/IUserService/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<UserStorage.Entity.User>> SearchAsync(UserStorage.Entity.UserCriteria criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Delete", ReplyAction="http://tempuri.org/IUserService/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClientApplication.ServiceReference.WcfServiceException), Action="http://tempuri.org/IUserService/DeleteWcfServiceExceptionFault", Name="WcfServiceException", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
        void Delete(UserStorage.Entity.User item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Delete", ReplyAction="http://tempuri.org/IUserService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(UserStorage.Entity.User item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : ClientApplication.ServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<ClientApplication.ServiceReference.IUserService>, ClientApplication.ServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(UserStorage.Entity.User item) {
            return base.Channel.Add(item);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(UserStorage.Entity.User item) {
            return base.Channel.AddAsync(item);
        }
        
        public System.Collections.Generic.List<UserStorage.Entity.User> Search(UserStorage.Entity.UserCriteria criteria) {
            return base.Channel.Search(criteria);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<UserStorage.Entity.User>> SearchAsync(UserStorage.Entity.UserCriteria criteria) {
            return base.Channel.SearchAsync(criteria);
        }
        
        public void Delete(UserStorage.Entity.User item) {
            base.Channel.Delete(item);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(UserStorage.Entity.User item) {
            return base.Channel.DeleteAsync(item);
        }
    }
}
